version: "3.8"
services:
 app:
   build: ./
   container_name: app
   ports:
     - '3000:3000'
   restart: unless-stopped
   env_file:
     - .env
   volumes:
     - '.:/app'
   depends_on:
     - db
 db:
   image: postgres:alpine
   container_name: app_postgres
   restart: always
   ports:
     - '5433:5432'
   environment:
     - POSTGRES_PASSWORD=${PASSWORD_DB}
     - POSTGRES_USER=${USERNAME_DB}
     - POSTGRES_DB=${NAME_DB}
   volumes:
     - './initdb.sql:/docker-entrypoint-initdb.d/initdb.sql'
     - 'pg-data:/var/lib/postgresql/data'
volumes:
  pg-data:
