version: "3.8"
services:
 app:
   build: .
   container_name: app
   ports:
     - '3000:3000'
   restart: unless-stopped
   env_file:
     - .env
   depends_on:
     - db
 db:
   image: postgres:alpine
   container_name: app_postgres
   restart: always
   ports:
     - '5432:5432'
   environment:
     - POSTGRES_PASSWORD=${PASSWORD_DB}
     - POSTGRES_USER=${USERNAME_DB}
     - POSTGRES_DB=${NAME_DB}
   volumes:
     - './internal/postgres/v1.0/v1.01:/docker-entrypoint-initdb.d'
     - 'pg-data:/var/lib/postgresql/data'
volumes:
  pg-data:
